### ISSUE TITLE
dijit/Viewport:global variable orientation not defined on ios

### ISSUE THREAD

**Issue by dylans** [dojo/dijit#139]
@sebastianfrey commented on [Wed Mar 21 2018](https://github.com/dojo/dojo/issues/291)

Hi there,

Saddly I am not able to submit a ticket at [https://bugs.dojotoolkit.org/newticket#ticket](https://bugs.dojotoolkit.org/newticket#ticket), beacuse the spam mechanismn blocks me. So I submit the issue here, since at the dijit repo no issue section is available and the issue is dijit related. Sry for that. The related dojo version is 1.10.4..

The issue is, that DropDown's of dijit/form/FilteringSelect Elements are not shown on iOS. I think, I could nail down the reason for failing on iOS  to dijit/Viewport.getEffectiveBox().

```js
Viewport.getEffectiveBox = function(/*Document*/ doc){	
	// summary:
	//		Get the size of the viewport, or on mobile devices, the part of the viewport not obscured by the
	//		virtual keyboard.

	var box = winUtils.getBox(doc);

	// Account for iOS virtual keyboard, if it's being shown.  Unfortunately no direct way to check or measure.
	var tag = focusedNode && focusedNode.tagName && focusedNode.tagName.toLowerCase();
	if(has("ios") && focusedNode && !focusedNode.readOnly && (tag == "textarea" || (tag == "input" &&
		/^(color|email|number|password|search|tel|text|url)$/.test(focusedNode.type)))){

		// Box represents the size of the viewport.  Some of the viewport is likely covered by the keyboard.
		// Estimate height of visible viewport assuming viewport goes to bottom of screen, but is covered by keyboard.
		box.h *= (orientation == 0 || orientation == 180 ? 0.66 : 0.40);

		// Above measurement will be inaccurate if viewport was scrolled up so far that it ends before the bottom
		// of the screen.   In this case, keyboard isn't covering as much of the viewport as we thought.
		// We know the visible size is at least the distance from the top of the viewport to the focused node.
		var rect = focusedNode.getBoundingClientRect();
		box.h = Math.max(box.h, rect.top + rect.height);
	}

	return box;
};
```

There is  a peace of code just for iOS included, which takes account for the virtual keyboard on iOS. So if a user hits the FilteringSelect, the above iOS specific peace of code, will be executed. The problem with this peace of code is, that there the global variable `orientation` is referenced directly, but it seems that `orientation` is not supported on Safari in general. [https://caniuse.com/#feat=screen-orientation](https://caniuse.com/#feat=screen-orientation). 

Again sry for submiting the issue here and thanks for looking into it.

Regards
Sebastian

---

@dylans commented on [Wed Mar 21 2018](https://github.com/dojo/dojo/issues/291#issuecomment-374928598)

I have gone ahead and enabled issues for dojo/dijit as well. I'm going to move this issue over there.

**Comment by dylans** [comment]
@sebastianfrey the first thing I would ask is, have you tried this with a more recent version of Dijit as 1.10.4 is several years old. Trying 1.10.9 should be a relatively trivial change. Also, I assume this is an issue with iOS 11.x?

**Comment by sebastianfrey** [comment]
@dylans 
I tried it also with 1.12.2 and there the error also occurs. The Issue occurs on iOS11.x, but also on iOS 10.x.

**Comment by wkeese** [comment]
Hmm, strange, it used to work, but not sure which version of iOS.  Whichever was the latest version when I wrote that code.  `window.orientation` also doesn't work?  (I mean, `window.orientation` doesn't have a meaningful value?)

You can see from http://www.williammalone.com/articles/html5-javascript-ios-orientation/ that it is (or was) an actual thing.

**Comment by sebastianfrey** [comment]
As it seems, I need to redo my researches with a physical device, because the emulator used for debugging, does not set the property. So that fact leaded me to make the wrong assumption. When I have done this, I will give you feedback again.

**Comment by sebastianfrey** [comment]
As it tourned out, I was missled by the emulator I used for testing. On a physical device the error does not occure anymore. So this issue might be closed.

**Comment by dylans** [comment]
No worries, thanks!
