### ISSUE TITLE
dateTextBox will flag a date as invalid while it's being typed

### ISSUE THREAD

**Issue by nmfriesen** [dojo/dijit#148]
When you have a dateTextBox with min and/or max constraints on it, you can get an out of range indicator while you’re typing a valid date. For example if you have a dateTextBox with a valid range of 3/21/2018 to 3/31/2018 and you type 3/25/20 you will get an out of range message. I would expect this to see that adding 18 would make this a valid value, and not show the indicator until the control lost focus.

**Comment by msssk** [comment]
`dijit/DateTextBox` does account for values that are [incomplete](https://github.com/dojo/dijit/blob/fb7b0b53191bc7f2c62c3085ed31909aab5ec1f9/form/ValidationTextBox.js#L112-L117). The problem in your example is that "3/25/20" can be interpreted as a complete value, in which case it is interpreted as "3/25/2020", which is out of range.
