### ISSUE TITLE
DOMException: Failed to execute 'querySelectorAll' on '[group=group1] [role=role1]' is not a valid selector.

### ISSUE THREAD

**Issue by luiscla27** [dojo/dijit#152]
Hello,

It seems that the selectorEngine ["lite"](https://dojotoolkit.org/reference-guide/1.10/dojo/query.html#selector-engines) isn't well implementated at "dijit/RadioButtonMenuItem", currently you have the following code with the uncompatibility:

`

			
		_getRelatedWidgets: function(){
			// Private function needed to help iterate over all radio menu items in a group.
			var ary = [];
			query("[group=" + this.group + "][role=" + this.role + "]").forEach(
				function(menuItemNode){
					var widget = registry.getEnclosingWidget(menuItemNode);
					if(widget){
						ary.push(widget);
					}
				}
			);
			return ary;
		}
`
I think you need to change the query to:

`
query("[group='" + this.group + "'][role='" + this.role + "']")
`

**Comment by luiscla27** [comment]
I'll make a pull request fixing this as soon as someone here accept this is an actual issue... thanks.

**Comment by msssk** [comment]
What browser are you seeing this error in?

The [CSS 2](https://www.w3.org/TR/CSS2/selector.html#attribute-selectors) (and 3) specs show examples with unquoted values. I tested the lite engine (which delegates to the browser's `querySelectorAll` implementation when available) in Chrome 80, Firefox 74, and IE 11, and in all cases the code above works.

**Comment by luiscla27** [comment]
This was caused by the issue tested [here](https://github.com/dojo/dojox/issues/284#issuecomment-412382216). It was a Google Chrome bug, they fixed it pretty fast, so there was no reason to make a PR.
