### ISSUE TITLE
dijit/Dialog shows vertical scrollbar even though not necessary

### ISSUE THREAD

**Issue by janschatz** [dojo/dijit#154]
When a dijit/Dialog has no size constraints and the dialog becomes to wide for the viewport, it will limit the width to 90 % of the viewport. However, it will fix the height at the same time. This will prevent the dialog from growing in height due to word wraps etc. So vertical scrollbars may be shown even though not necessary. Even worse: while decreasing the viewport width, the scrollbars will be shown/hidden all the time.

I have created a [fiddle](http://jsfiddle.net/bscg2L3x/) demonstrating the issue.

The following images show what happens when you decrease the viewport size:
![screenshot_2018-08-06 dojo layout in dialog - jsfiddle](https://user-images.githubusercontent.com/13834416/43722090-cd623154-9994-11e8-8950-41f121a7790c.png)
![screenshot_2018-08-06 dojo layout in dialog - jsfiddle 1](https://user-images.githubusercontent.com/13834416/43722099-d3c5b85e-9994-11e8-87fb-4896134fb73a.png)
![screenshot_2018-08-06 dojo layout in dialog - jsfiddle 2](https://user-images.githubusercontent.com/13834416/43722101-d5af725e-9994-11e8-95c0-a9b7bbf1d855.png)
![screenshot_2018-08-06 dojo layout in dialog - jsfiddle 3](https://user-images.githubusercontent.com/13834416/43722109-d768a958-9994-11e8-8c60-4f8e30eb5084.png)

**Comment by dylans** [comment]
Closed via 1bc6650.
