### ISSUE TITLE
Dialog with draggable:false opened through popup.open() with an around area still shows a move cursor

### ISSUE THREAD

**Issue by nzall** [dojo/dijit#165]
I have a page with a custom tab where the onClose opens a confirmation dialog. The below is the confirmation dialog:

    <div data-dojo-type="dijit/Dialog"
		data-dojo-props="title:'<s:property value="%{getText('label.desktop.removeDesktop')}"/>', draggable: false"
		id="desktopRemoveDialog" style="display: none;">

		<div class="c-panel-dialog">
			<p class="c-panel-dialog__header">
				<s:property value="%{getText('label.desktop.removeDesktop')}" />
			</p>
			<div>
				<span id="removeDesktopConfirmationText" class="c-global-message c-global-message--error"></span>
			</div>
			<div class="l-panel-bottom-actions-wrapper u-margin-t-xs">
				<input id="removeDesktopOkButton"
					value="<s:property value="%{getText('button.delete')}"/>"
					type="button" class="c-button"> <input
					id="removeDesktopCancelButton"
					value="<s:property value="%{getText('button.cancel')}"/>"
					type="button" class="c-button">
			</div>
		</div>
	</div>

The code to open this dialog is as such:

    function onRemoveDesktop(tab) {
		textSpan = dom.byId("tabSpan" + tab.desktopOid);
		theRemoveConfirmationText = dom.byId("removeDesktopConfirmationText");
		theRemoveConfirmationText.innerHTML = removeDesktopConfirmationMessage.replace("{0}", "'" + textSpan.innerHTML + "'");
		registry.byId("desktopRemoveDialog").tab = tab;
		tabArea = dom.byId(tab.controlButton.id);
		popup.open({ //regular dijit/popup
			popup : registry.byId("desktopRemoveDialog"),
			around : tabArea
		});
	}

I have 2 more tabs for editing and adding a tab that are handled through pretty much the same technique. In this particular combination of actions, it seems like the dialog doesn't get the dijitDialogFixed class that disabled the cursor:move CSS rule on the dialog title. I have another regular dialog on this page that is opened normally, and adding draggable: false to this dialog's data-dojo-props does properly apply the CSS rule.

Dojo version: 1.9.3. I know it's an older version, so if this is fixed in a newer version, feel free to close this.

**Comment by msssk** [comment]
`dijit/Dialog` was not designed to be used this way. A significant part of the reasoning for using `dijit/Dialog` is the functionality provided in the `show/hide` methods. Some other options that may be more helpful in this scenario are [`dijit/TooltipDialog`](https://dojotoolkit.org/reference-guide/1.10/dijit/TooltipDialog.html) and [`dijit/_HasDropDown`](https://dojotoolkit.org/reference-guide/1.10/dijit/_HasDropDown.html).
