### ISSUE TITLE
dijit.Tree with betweenThreshold not compatible with dojo/store/Memory

### ISSUE THREAD

**Issue by sm-Fifteen** [dojo/dijit#170]
`betweenThreshold`, which lets users manually reorder elements by dragging them between others in the tree, appears to be incompatible with the Memory storage system. Dragging an element between two others using that configuration causes it to disappear, as highlighted by [this snippet of code in the ObjectStoreModel](https://github.com/dojo/dijit/blob/0e35b944315b9e719f21e6c28c9993cf8cd99636/tree/ObjectStoreModel.js#L221-L227) which, while it does adress the issue with the default tree config, still causes the problem to occur when manual reordering is enabled.

Steps to reproduce:
* Take [the drag and drop example from the documentation](https://dojotoolkit.org/reference-guide/1.10/dijit/Tree.html#drag-and-drop) and add `betweenThreshold : 5` to the tree options.
* Run the code and try dragging "South America" between "Africa" and "Asia"

EDIT: [See related issue on the old tracker](https://bugs.dojotoolkit.org/ticket/18142).

**Comment by sm-Fifteen** [comment]
Current solution is to override `pasteItem` on the ObjectStoreModel to properly reorder the data internally and `put` on the Memory store to send an event after the update has completed, like so:

```js
memoryStore.put = function(object, options) {
    // Modified version of the stock put function to support element reordering

    var data = this.data, index = this.index, idProperty = this.idProperty;
    var id = object[idProperty] = (options && "id" in options) ? options.id : idProperty in object ? object[idProperty] : Math.random();

    var beforeIdx;
    var originalId = undefined;

    if(id in index){
        // object exists
        if(options && options.overwrite === false){
            throw new Error("Object already exists");
        }

        // pasteItem may remove the element beforehand (isCopy indicates whether or not it did)
        // We don't want to try removing it if that's the case.
        if (options && options.isCopy !== undefined) {
            // Remove the object from its previous position
            data.splice(index[id], 1);
            originalId = id;
        }
    }

    // https://dojotoolkit.org/api/#1_10dojo_store_api_Store_put
    // `before`: "A value of null indicates that the object should be last."

    // Index may be dirty, use indexOf instead
    if (options && options.before) beforeIdx = data.indexOf(options.before);

    if (beforeIdx === undefined) {
        // Append at the end and update index
        data.push(object);
    } else {
        // Splice in position and reindex
        data.splice(beforeIdx, 0, object);
    }

    this.setData(data); // How `dojo/store/Memory` performs reindexing internally

    return originalId; // The stock version gets this wrong, no id should be returned on insert
}
```

```js
aspect.around(myModel, "pasteItem", function(originalPaste){
    return function(childItem, oldParentItem, newParentItem, bCopy, insertIndex, before){
        var getChildren = this.getChildren.bind(this, newParentItem);
        var onChildrenChange = this.onChildrenChange;

        var pastePromise = originalPaste.call(this, childItem, oldParentItem, newParentItem, bCopy, insertIndex, before);

        // Reset the cache, otherwise getChildren will return outdated data.
        this.childrenCache = {};

        pastePromise.then(function(originalId) {
            getChildren(function(newChildren) {
                onChildrenChange(newParentItem, newChildren);
            });
        });
    }
});
```

Not sure if I should throw that in a pull request considering the proposed code makes suboptimal use of the Memory index and that it doesn't adress the issue for other stores. Regardless, I believe the issue should be resolved if the ObjectStore API is to replace the old data API, since people wanting to use Tree for drag and drop operations have to fallback on ItemFileWriteStore.

**Comment by wkeese** [comment]
Yeah, I remember this being broken, see https://bugs.dojotoolkit.org/ticket/15660 (also https://bugs.dojotoolkit.org/ticket/15661, https://bugs.dojotoolkit.org/ticket/16516).

**Comment by sm-Fifteen** [comment]
Seems like I'm not the first person to suggest code changes, any reason why those have been on hold since 2013? There's mentions of dstore fixing the issue but it still hasn't replaced dojo/store internally, and that "requirement" isn't expressed anywhere.

**Comment by wkeese** [comment]
Sorry, the code just isn't maintained anymore, except maybe for patches people submit.
