### ISSUE TITLE
TabContainer issue in IE11

### ISSUE THREAD

**Issue by prabhuofficial** [dojo/dijit#175]
TabContainer in IE is not rendering content in tabbed fashion, instead renders as vertical content. Please help me to resolve this issue.

Note:Even CodeGlass example listed in documentation renders that way
![IE](https://user-images.githubusercontent.com/4505806/68481674-da8b5580-025d-11ea-9883-1e7de41b8666.PNG)

**Comment by wkeese** [comment]
Maybe it's just codeglass that's failing.  https://download.dojotoolkit.org/release-1.9.0/dojo-release-1.9.0/dijit/tests/layout/test_TabContainer.html works fine on IE11 and I suspect the newer dojo releases do too.
