### ISSUE TITLE
dijit/form/Select multi-select

### ISSUE THREAD

**Issue by gsexton** [dojo/dijit#176]
Everyone,

I'm trying to use dijit/form/Select. The reason I've chosen it is that I need the ability to style the elements. I'd also like to do multi-select. I see that "multiple" is documented as a property for this object. My code is:

```
<div value="1"   data-dojo-type="dijit/form/Select"  id="IDwbs" multiple="true" name="wbs" >
<span value="3"><span style="background-color: purple; color: white; padding: 4px;">0.1.2 + The Master</span></span>
<span value="1" ><span style="margin-left: 1em; font-weight: bold; color: white; background-color: teal;">1.2.3 + The Barn</span></span>
<span value="2"><span style="margin-left: 2em">2.3.4 + The Granary</span></span>
</div>
```
I've also tried:

```
<div value="1"   data-dojo-type="dijit/form/Select"  id="IDwbs" multiple  name="wbs" >
AND
<div value="1"   data-dojo-type="dijit/form/Select"  id="IDwbs" data-dojo-props="multiple: true" name="wbs" >
```

Does this element support multi-select? Is there a multi-select that supports using styles?

Thanks for the help!

George

**Comment by msssk** [comment]
`dijit/form/Select` does not support multiple values. The [`dijit/form/MultiSelect`](https://dojotoolkit.org/reference-guide/1.10/dijit/form/MultiSelect.html) widget does, but it is based on the native browser select with limited styling. The [`dojo/form/CheckedMultipleSelect`](https://dojotoolkit.org/reference-guide/1.10/dojox/form/CheckedMultiSelect.html) widget may meet your needs.
