### ISSUE TITLE
Add child fails while adding a TitlePane to layout 

### ISSUE THREAD

**Issue by ashishraina** [dojo/dijit#198]
After upgrading the product to 1.17, on debug found that below code misses check for refNode. This code check was there in earlier versions
 ```
declare("dijit._Container", null, {
		addChild: function(/*dijit/_WidgetBase*/ widget, /*int?*/ insertIndex){
			var refNode = this.containerNode;
			if(insertIndex > 0){
				refNode = refNode.firstChild;
				// There is missing null check for refNode, this fails while adding objects
                               while(insertIndex > 0){
					if(refNode.nodeType == 1){ insertIndex--; }
					refNode = refNode.nextSibling;
				}
```

**Comment by wkeese** [comment]
I guess you're talking about the change c7b1d29e31e2b209966ee902f3d5c5f0e6299c60 from 10 years ago?

All this code is ancient and would be written very differently today, but having said that, if you call `addChild(widget, 123)`, isn't it reasonable to assume that the parent widget has at least 123 children?

**Comment by ashishraina** [comment]
Ok I got it, as we had only upgraded dojo so we wanted to ensure nothing is broken and the dojo code we have had that extra check on refNode (maybe that was added locally). In the widget making call to this method, the addChild was starting from insertIndex = 1, and was hence failed as the extra check was missing as we took the toolkit as is.
Now changing the widget addChild to start from insertIndex=0 fixes the issue.
Still a check like below would have been good but I understand how it is meant to be used, so it is okay.
```
                               refNode = refNode.firstChild;
				if(refNode){
					while(refNode && insertIndex > 0){
						if(refNode.nodeType == 1){ insertIndex--; }
						refNode = refNode.nextSibling;
					}
				}
				if(refNode){
					insertIndex = "before";
				}else{
					// to support addChild(child, n-1) where there are n children (should add child at end)
					refNode = this.containerNode;
					insertIndex = "last";
				}
```

**Comment by wkeese** [comment]
OK, glad you fixed the issue.

I tend to agree with you that a check for `refNode` being `null` would be good, although "the best thing to do when you get passed illegal arguments" is kind-of a philosophical question.  Historically, dojo picked whatever option was the least amount of code.

The main thing I don't understand/remember is why I didn't just use `refNode.children` to get the children.  That's the straightforward way to skip comments and text nodes, and skip looping too.
